# Generated by Django 3.1.2 on 2020-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubefeed',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
