# Generated by Django 3.1.2 on 2020-12-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0002_auto_20201203_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('artist', models.CharField(blank=True, max_length=50)),
                ('file_location', models.ImageField(upload_to='', verbose_name='Music file directory')),
            ],
        ),
    ]
