# Generated by Django 3.1.2 on 2020-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0003_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
    ]
