# Generated by Django 3.1.2 on 2020-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='youtubefeed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
