# Generated by Django 3.1.2 on 2020-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0006_auto_20201203_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
