# Generated by Django 3.1.2 on 2020-12-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0008_auto_20201203_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('hotline', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
