# Generated by Django 3.1.2 on 2020-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0013_auto_20201204_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
