# Generated by Django 3.1.2 on 2020-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0016_auto_20201204_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
