# Generated by Django 3.1.2 on 2020-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0018_auto_20201204_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
