# Generated by Django 3.1.2 on 2020-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0021_remove_event_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
