# Generated by Django 3.1.2 on 2020-12-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0022_auto_20201204_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
