# Generated by Django 3.1.2 on 2020-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0023_auto_20201204_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
