# Generated by Django 3.1.2 on 2020-12-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0024_auto_20201204_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
