# Generated by Django 3.1.4 on 2020-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0025_auto_20201204_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
