# Generated by Django 3.1.4 on 2020-12-05 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Banjo', '0026_auto_20201205_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
